#!/usr/bin/env bash

# Aliases and Functions
## Commands
# shellcheck disable=SC2046
randword() { set -- $(openssl rand -hex 8 | mnencode -x 2>/dev/null); echo "$1" ;}

## Development
alias bemar="bundle exec middleman article"
alias bemid="bundle exec middleman"
alias bemse="bundle exec middleman server"
alias berse="bundle exec rails server"

## Sudo aliases
alias sagup="sudo apt-get update"
alias saguq="sudo apt-get update -qq"
alias sagiy="sudo apt-get install -y"

## Vagrant aliases
alias svagr="ssh vagrant"
alias vdest="vagrant destroy"
alias vgsta="vagrant global-status"
alias vhalt="vagrant halt"
alias vinit="vagrant init"
alias vrelo="vagrant reload"
alias vssh="vagrant ssh"
alias vstat="vagrant status"
alias vup="vagrant up"
