#!/usr/bin/env bash

! which vboxmanage >/dev/null || exit 0
echo "deb http://download.virtualbox.org/virtualbox/debian wily contrib" | sudo tee /etc/apt/sources.list.d/virtualbox.list > /dev/null
wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
sudo apt-get update -qq
sudo apt-get install -y virtualbox-5.0
