#!/usr/bin/env bash

dpkg --get-selections numix-gtk-theme | grep -q '^numix-gtk-theme[[:space:]]\\+install$' && exit
sudo add-apt-repository -y ppa:numix/ppa
sudo apt-get update -qq
sudo apt-get install -y numix-gtk-theme numix-icon-theme numix-icon-theme-circle numix-wallpaper-notd
