---

- name:         Setup user
  hosts:        127.0.0.1
  connection:   local
  gather_facts: no

  tasks:
    - name: directories
      file:
        path:   $HOME/{{ item }}
        state:  directory
        mode:   '755'
      loop:
        - .config/liquidprompt
        - tmp

    - name: utilities
      homebrew:
        name:
          - ranger
          - stgit
          - neovim
          - tmux

    - name: repos
      git:
        repo:   "{{ item.repo }}"
        dest:   $HOME/{{ item.dest }}
        update: yes
      loop:
        - { repo: git://github.com/binaryphile/dotfiles,  dest: dotfiles      }
        - { repo: git://github.com/binaryphile/dot_vim,   dest: .config/nvim  }

    - name: dotfile links
      file:
        src:    $HOME/dotfiles/{{ item.src }}
        path:   $HOME/{{ item.path }}
        state:  link
        force:  yes
      loop:
        - { src: bash/bashrc,                 path: .bash_profile                     }
        - { src: bash/bashrc,                 path: .bashrc                           }
        - { src: gitconfig,                   path: .gitconfig                        }
        - { src: liquidprompt/liquid.theme,   path: .config/liquidprompt/liquid.theme }
        - { src: liquidprompt/liquidprompt,   path: .config/liquidprompt/liquidprompt }
        - { src: liquidprompt/liquidpromptrc, path: .config/liquidpromptrc            }
        - { src: ssh/config,                  path: .ssh/config                       }
        - { src: tmux.conf,                   path: .tmux.conf                        }

    - name: links
      file:
        src:    "{{ item.src }}"
        path:   $HOME/{{ item.path }}
        state:  link
      loop:
        - { src: $HOME/.config/nvim, path: .vim }

    - name: context link
      file:
        src:    contexts/office/macos
        path:   $HOME/dotfiles/context
        state:  link
