---

- name:         Setup user
  hosts:        all
  gather_facts: no

  tasks:
    - name: directories
      file:
        path:   $HOME/{{ item }}
        state:  directory
        mode:   '755'
      loop:
        - .config/liquidprompt
        - tmp

    - name: repos
      git:
        repo:   "{{ item.repo }}"
        dest:   $HOME/{{ item.dest }}
        update: yes
      loop:
        - { repo: "git://github.com/binaryphile/dotfiles",  dest: dotfiles                  }
        - { repo: "git://github.com/binaryphile/dot_vim",   dest: .vim,     branch: minimal }

    - name: dotfile links
      file:
        src:    $HOME/dotfiles/{{ item.src }}
        path:   $HOME/{{ item.path }}
        state:  link
        force:  yes
      loop:
        - { src: bash/bashrc,                 path: .bash_profile                     }
        - { src: bash/bashrc,                 path: .bashrc                           }
        - { src: bash/bashrc,                 path: .profile                          }
        - { src: bash/dir_colors,             path: .dir_colors                       }
        - { src: gitconfig,                   path: .gitconfig                        }
        - { src: liquidprompt/liquid.theme,   path: .config/liquidprompt/liquid.theme }
        - { src: liquidprompt/liquidpromptrc, path: .config/liquidpromptrc            }
        - { src: ssh/config,                  path: .ssh/config                       }

    - name: context link
      file:
        src:    contexts/digi/ubuntu-14
        path:   $HOME/dotfiles/context
        state:  link
