#!/usr/bin/env bash

dpkg --get-selections nuvolaplayer3-google-play-music | grep -q '^nuvolaplayer3-google-play-music[[:space:]]\\+install$' && exit
pushd /etc/apt/sources.list.d >/dev/null
echo "deb https://tiliado.eu/nuvolaplayer/repository/deb/ wily stable" | sudo tee tiliado-nuvolaplayer.list > /dev/null
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 40554B8FA5FE6F6A
sudo apt-get update -qq
sudo apt-get install -y nuvolaplayer3-google-play-music
popd >/dev/null
