#!/usr/bin/env bash

which dropbox >/dev/null && exit
mkdir -p "$HOME"/Downloads
pushd "$HOME"/Downloads >/dev/null
wget https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2015.10.28_amd64.deb
sudo dpkg -i dropbox_*_amd64.deb
rm dropbox_*_amd64.deb
popd >/dev/null
