#!/usr/bin/env bash

Prog=$(basename "$0")
Version=0.1

read -rd '' Usage_ <<END
Usage:

  $Prog [OPTIONS] [--] COMMAND [ARGS...]

  setup         clone urma-next repo and install

  Options:

    -h | --help     show this message and exit
    -v | --version  show the program version and exit
    -x | --trace    enable debug tracing
END

## commands

cmd.setup() (
  [[ -e $FontAwesomeKeyFile ]] || mk.Fatal "missing fontawesome token file: $FontAwesomeKeyFile"
  mk.Each mk.Cue <<'  END'
    git clone git@stash.digi.com:idigi/urma-next ~/urma-next
    cd ~/urma-next/urma-next/scripts
    git checkout -b local origin/tlilley/local
  END
  export FONTAWESOME_PACKAGE_TOKEN=$(<~/fa-token.txt)
  mk.Cue ./urma install

  # obsidian is a non-submodule sub-repo (its own git repo, gitignored by parent)
  if [[ ! -d ~/projects/urma/obsidian/.git ]]; then
    mk.Cue git clone git@stash.digi.com:~tlilley/urma-obsidian ~/projects/urma/obsidian
  fi
)

## globals

FontAwesomeKeyFile=~/secrets/fontawesome.key

## boilerplate

source "${MK_BASH_LIB:?mk.bash not installed -- run home-manager switch}"

IFS=$'\n'
set -o noglob

mk.SetProg $Prog
mk.SetUsage "$Usage_"
mk.SetVersion $Version

return 2>/dev/null
mk.HandleOptions "$@"
mk.Main "${@:$?}"
