#!/usr/bin/env bash

Prog=$(basename "$0")
Version=0.1

read -rd '' Usage_ <<END
Usage:

  $Prog [OPTIONS] [--] COMMAND [ARGS...]

  setup         clone urma-obsidian sibling under ~/projects/digi/

  Options:

    -h | --help     show this message and exit
    -v | --version  show the program version and exit
    -x | --trace    enable debug tracing
END

## commands

cmd.setup() (
  # urma-obsidian is the operator's personal obsidian vault for urma research,
  # cloned as a sibling of urma under ~/projects/digi/ per tasks.jeeves #20568.
  # urma-next itself is cloned by update-env's urma section (stashCloneAndLinkTask).
  if [[ ! -d ~/projects/digi/urma-obsidian/.git ]]; then
    mk.Cue git clone git@stash.digi.com:~tlilley/urma-obsidian ~/projects/digi/urma-obsidian
  fi
)

## boilerplate

source "${MK_BASH_LIB:?mk.bash not installed -- run home-manager switch}"

IFS=$'\n'
set -o noglob

mk.SetProg $Prog
mk.SetUsage "$Usage_"
mk.SetVersion $Version

return 2>/dev/null
mk.HandleOptions "$@"
mk.Main "${@:$?}"
