#!/usr/bin/env bash

fzf=$HOME/dotfiles/bash/fzf.bash
chruby=/usr/local/share/chruby/chruby.sh
chruby_auto=/usr/local/share/chruby/auto.sh
! [[ -f $fzf    ]]  || source "$fzf"
! [[ -f $chruby ]]  || {
  source "$chruby"
  source "$chruby_auto"
}
unset -v fzf chruby chruby_auto

nixrc="$HOME"/.nix-profile/etc/profile.d/nix.sh
[[ -f $nixrc ]] && source "$nixrc"
unset -v nixrc

# Aliases and Functions
## Commands

## Development
alias bemar="bundle exec middleman article"
alias bemid="bundle exec middleman"
alias bemse="bundle exec middleman server"

## Sudo aliases
alias sagup="sudo apt-get update"
alias saguq="sudo apt-get update -qq"
alias sagiy="sudo apt-get install -y"

## Vagrant aliases
alias vdest="vagrant destroy"
alias vhalt="vagrant halt"
alias vstat="vagrant status"
alias vup="vagrant up"

# Interactive shell only
# ======================
[[ $- != *i* ]] && return
source "$HOME"/.config/liquidprompt/liquidprompt
