# Get shared aliases/functions like "psaux"
sharedrc=/opt/app/avwobt4/share/bash/sharedrc
[[ -e $sharedrc ]] && source "$sharedrc"
unset -v sharedrc

export BASHER_ROOT=${BASHER_ROOT:-/opt/app/avwobt4}

less=$(type -p less) && export PAGER=$less
unset -v less

export GIT_DISCOVERY_ACROSS_FILESYSTEM=${GIT_DISCOVERY_ACROSS_FILESYSTEM:-1}
