#!/usr/bin/env bash

export GIT_DISCOVERY_ACROSS_FILESYSTEM=${GIT_DISCOVERY_ACROSS_FILESYSTEM:-1}

[[ $- == *i* ]] || return

type gdb >/dev/null 2>&1 && {
  gdb <<EOF >/dev/null 2>&1
  attach $$
  call unbind_variable("TMOUT")
  detach
  quit
EOF
}
